import cv2
import face_recognition
import numpy as np
import pickle
import os
import csv
from datetime import datetime

# Path to the encodings file generated by encode_faces.py
ENCODINGS_FILE = "encodings.pickle"
ATTENDANCE_FILE = "attendance/attendance.csv"

# Blink detection settings
EYE_AR_THRESH = 0.25
EYE_AR_CONSEC_FRAMES = 2

def eye_aspect_ratio(eye):
    # eye is a list of 6 (x, y) tuples
    # compute the euclidean distances between the two sets of vertical eye landmarks
    A = np.linalg.norm(np.array(eye[1]) - np.array(eye[5]))
    B = np.linalg.norm(np.array(eye[2]) - np.array(eye[4]))

    # compute the euclidean distance between the horizontal eye landmark
    C = np.linalg.norm(np.array(eye[0]) - np.array(eye[3]))

    # compute the eye aspect ratio
    ear = (A + B) / (2.0 * C)
    return ear

def mark_attendance(name):
    """
    Logs the attendance for a recognized face if they haven't been logged today.
    """
    if not os.path.exists('attendance'):
        os.makedirs('attendance')
        
    date_str = datetime.now().strftime("%Y-%m-%d")
    time_str = datetime.now().strftime("%H:%M:%S")

    # Read existing attendance to avoid duplicates on the same day
    # We can use a simple list since it's just for one day.
    attendees_today = []
    
    # Ensure the file exists
    if not os.path.exists(ATTENDANCE_FILE):
        with open(ATTENDANCE_FILE, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Name', 'Date', 'Time'])

    with open(ATTENDANCE_FILE, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            if row and row[1] == date_str:
                attendees_today.append(row[0])

    if name not in attendees_today:
        with open(ATTENDANCE_FILE, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([name, date_str, time_str])
        print(f"[ATTENDANCE] Logged {name} at {time_str}")


def run_attendance_system():
    # 1. Load the known faces and encodings
    print("[INFO] Loading encodings...")
    try:
        with open(ENCODINGS_FILE, "rb") as f:
            data = pickle.load(f)
        known_face_encodings = data["encodings"]
        known_face_names = data["names"]
    except FileNotFoundError:
        print(f"[ERROR] {ENCODINGS_FILE} not found. Please run encode_faces.py first.")
        return

    # 2. Initialize video stream
    print("[INFO] Starting video stream...")
    video_capture = cv2.VideoCapture(0) # 0 for default laptop camera
    
    blink_state = {} # Track blink frames and status per user

    while True:
        # Grab a single frame of video
        ret, frame = video_capture.read()
        if not ret:
            print("[ERROR] Failed to grab frame")
            break

        # Resize frame of video to 1/4 size for faster face recognition processing
        small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

        # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
        rgb_small_frame = cv2.cvtColor(small_frame, cv2.COLOR_BGR2RGB)
        
        # Find all the faces and face encodings in the current frame of video
        face_locations = face_recognition.face_locations(rgb_small_frame)
        face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)
        face_landmarks_list = face_recognition.face_landmarks(rgb_small_frame, face_locations)

        face_names = []
        for face_encoding, face_landmarks in zip(face_encodings, face_landmarks_list):
            # See if the face is a match for the known face(s)
            matches = face_recognition.compare_faces(known_face_encodings, face_encoding, tolerance=0.6)
            name = "Unknown"

            # Use the known face with the smallest distance to the new face
            face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
            if len(face_distances) > 0:
                best_match_index = np.argmin(face_distances)
                if matches[best_match_index]:
                    name = known_face_names[best_match_index]

            # Blink Detection Logic
            if name != "Unknown":
                if name not in blink_state:
                    blink_state[name] = {"consec_frames": 0, "has_blinked": False}
                
                left_eye = face_landmarks.get('left_eye')
                right_eye = face_landmarks.get('right_eye')
                
                if left_eye and right_eye:
                    leftEAR = eye_aspect_ratio(left_eye)
                    rightEAR = eye_aspect_ratio(right_eye)
                    ear = (leftEAR + rightEAR) / 2.0
                    
                    if ear < EYE_AR_THRESH:
                        blink_state[name]["consec_frames"] += 1
                    else:
                        if blink_state[name]["consec_frames"] >= EYE_AR_CONSEC_FRAMES:
                            blink_state[name]["has_blinked"] = True
                        blink_state[name]["consec_frames"] = 0

            face_names.append(name)
            
            # If we recognized a known face and they blinked, mark their attendance
            if name != "Unknown" and blink_state[name]["has_blinked"]:
                mark_attendance(name)

        # Display the results
        for (top, right, bottom, left), name in zip(face_locations, face_names):
            # Scale back up face locations since the frame we detected in was scaled to 1/4 size
            top *= 4
            right *= 4
            bottom *= 4
            left *= 4

            # Draw a box around the face
            if name == "Unknown":
                color = (0, 0, 255) # Red for unknown
                display_name = name
            elif not blink_state[name]["has_blinked"]:
                color = (0, 255, 255) # Yellow for known, waiting for blink
                display_name = f"{name} (Blink!)"
            else:
                color = (0, 255, 0) # Green for known and blinked
                display_name = name
                
            cv2.rectangle(frame, (left, top), (right, bottom), color, 2)

            # Draw a label with a name below the face
            cv2.rectangle(frame, (left, bottom - 35), (right, bottom), color, cv2.FILLED)
            font = cv2.FONT_HERSHEY_DUPLEX
            # Adjust text color for yellow box (black text for better visibility)
            text_color = (0, 0, 0) if color == (0, 255, 255) else (255, 255, 255)
            cv2.putText(frame, display_name, (left + 6, bottom - 6), font, 0.8, text_color, 1)

        # Display the resulting image
        cv2.imshow('Face Recognition Attendance', frame)

        # Hit 'q' on the keyboard to quit!
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release handle to the webcam
    video_capture.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    run_attendance_system()
